// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Data;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace Data.Configurations
{
    public partial class CardConfiguration : IEntityTypeConfiguration<Card>
    {
        public void Configure(EntityTypeBuilder<Card> entity)
        {
            entity.Property(e => e.Id).HasColumnName("id");

            entity.Property(e => e.Category)
                .HasMaxLength(10)
                .HasColumnName("category");

            entity.Property(e => e.DueDate)
                .HasMaxLength(5)
                .HasColumnName("due_date");

            entity.Property(e => e.IdType).HasColumnName("id_type");

            entity.Property(e => e.Number)
                .HasMaxLength(19)
                .HasColumnName("number");

            entity.Property(e => e.SecureCode).HasColumnName("secure_code");

            entity.HasOne(d => d.IdTypeNavigation)
                .WithMany(p => p.Card)
                .HasForeignKey(d => d.IdType)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Card__id_type__5441852A");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Card> entity);
    }
}
