// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Data;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace Data.Configurations
{
    public partial class CategorySubCategoryConfiguration : IEntityTypeConfiguration<CategorySubCategory>
    {
        public void Configure(EntityTypeBuilder<CategorySubCategory> entity)
        {
            entity.ToTable("Category_SubCategory");

            entity.Property(e => e.Id).HasColumnName("id");

            entity.Property(e => e.IdCategory).HasColumnName("id_category");

            entity.Property(e => e.IdSubcategory).HasColumnName("id_subcategory");

            entity.HasOne(d => d.IdCategoryNavigation)
                .WithMany(p => p.CategorySubCategory)
                .HasForeignKey(d => d.IdCategory)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Category___id_ca__4316F928");

            entity.HasOne(d => d.IdSubcategoryNavigation)
                .WithMany(p => p.CategorySubCategory)
                .HasForeignKey(d => d.IdSubcategory)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Category___id_su__440B1D61");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CategorySubCategory> entity);
    }
}
