// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Data;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace Data.Configurations
{
    public partial class HomeConfiguration : IEntityTypeConfiguration<Home>
    {
        public void Configure(EntityTypeBuilder<Home> entity)
        {
            entity.Property(e => e.Id).HasColumnName("id");

            entity.Property(e => e.Apartment).HasColumnName("apartment");

            entity.Property(e => e.House).HasColumnName("house");

            entity.Property(e => e.Number).HasColumnName("number");

            entity.Property(e => e.PostalCode).HasColumnName("postal_code");

            entity.Property(e => e.Street)
                .HasMaxLength(50)
                .HasColumnName("street");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Home> entity);
    }
}
