// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Data;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace Data.Configurations
{
    public partial class ProductSubCategoryConfiguration : IEntityTypeConfiguration<ProductSubCategory>
    {
        public void Configure(EntityTypeBuilder<ProductSubCategory> entity)
        {
            entity.ToTable("Product_SubCategory");

            entity.Property(e => e.Id).HasColumnName("id");

            entity.Property(e => e.IdProduct).HasColumnName("id_product");

            entity.Property(e => e.IdSubcategory).HasColumnName("id_subcategory");

            entity.HasOne(d => d.IdProductNavigation)
                .WithMany(p => p.ProductSubCategory)
                .HasForeignKey(d => d.IdProduct)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Product_S__id_pr__46E78A0C");

            entity.HasOne(d => d.IdSubcategoryNavigation)
                .WithMany(p => p.ProductSubCategory)
                .HasForeignKey(d => d.IdSubcategory)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Product_S__id_su__47DBAE45");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProductSubCategory> entity);
    }
}
