// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Data;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace Data.Configurations
{
    public partial class ShopCartConfiguration : IEntityTypeConfiguration<ShopCart>
    {
        public void Configure(EntityTypeBuilder<ShopCart> entity)
        {
            entity.Property(e => e.Id).HasColumnName("id");

            entity.Property(e => e.CartSubtotal)
                .HasColumnType("decimal(18, 0)")
                .HasColumnName("cart_subtotal");

            entity.Property(e => e.IdClient).HasColumnName("id_client");

            entity.Property(e => e.IdProduct).HasColumnName("id_product");

            entity.Property(e => e.ProductSubtotal)
                .HasColumnType("decimal(18, 0)")
                .HasColumnName("product_subtotal");

            entity.Property(e => e.Stock).HasColumnName("stock");

            entity.HasOne(d => d.IdClientNavigation)
                .WithMany(p => p.ShopCart)
                .HasForeignKey(d => d.IdClient)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ShopCart__id_cli__4E88ABD4");

            entity.HasOne(d => d.IdProductNavigation)
                .WithMany(p => p.ShopCart)
                .HasForeignKey(d => d.IdProduct)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ShopCart__id_pro__4F7CD00D");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ShopCart> entity);
    }
}
