// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data
{
    public partial class CardType
    {
        public CardType()
        {
            Card = new HashSet<Card>();
        }

        public int Id { get; set; }
        public string Description { get; set; }

        public virtual ICollection<Card> Card { get; set; }
    }
}