// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data
{
    public partial class Card
    {
        public int Id { get; set; }
        public string Category { get; set; }
        public string Number { get; set; }
        public string DueDate { get; set; }
        public int? SecureCode { get; set; }
        public int IdType { get; set; }

        public virtual CardType IdTypeNavigation { get; set; }
    }
}