// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Data.Configurations;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
#nullable disable

#nullable disable

namespace Data
{
    public partial class EcommerceContext : DbContext
    {
        public EcommerceContext()
        {
        }

        public EcommerceContext(DbContextOptions<EcommerceContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Action> Action { get; set; }
        public virtual DbSet<Card> Card { get; set; }
        public virtual DbSet<CardType> CardType { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<CategorySubCategory> CategorySubCategory { get; set; }
        public virtual DbSet<Home> Home { get; set; }
        public virtual DbSet<Issue> Issue { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductSubCategory> ProductSubCategory { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<ShopCart> ShopCart { get; set; }
        public virtual DbSet<SubCategory> SubCategory { get; set; }
        public virtual DbSet<Users> Users { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "Modern_Spanish_CI_AS");

            modelBuilder.ApplyConfiguration(new Configurations.ActionConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.CardConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.CardTypeConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.CategoryConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.CategorySubCategoryConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.HomeConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.IssueConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.MenuConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ProductConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ProductSubCategoryConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.RolConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ShopCartConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.SubCategoryConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.UsersConfiguration());
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
