// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data
{
    public partial class Home
    {
        public Home()
        {
            Users = new HashSet<Users>();
        }

        public int Id { get; set; }
        public bool House { get; set; }
        public bool Apartment { get; set; }
        public string Street { get; set; }
        public int Number { get; set; }
        public int PostalCode { get; set; }

        public virtual ICollection<Users> Users { get; set; }
    }
}