// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data
{
    public partial class Issue
    {
        public int Id { get; set; }
        public string Issue1 { get; set; }
        public string Response { get; set; }
        public DateTime? IssueDate { get; set; }
        public DateTime? ResponseDate { get; set; }
        public int IdClient { get; set; }
        public int IdAdmin { get; set; }

        public virtual Users IdAdminNavigation { get; set; }
        public virtual Users IdClientNavigation { get; set; }
    }
}