// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data
{
    public partial class Menu
    {
        public int Id { get; set; }
        public string Description { get; set; }
    }
}