// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data
{
    public partial class Product
    {
        public Product()
        {
            ProductSubCategory = new HashSet<ProductSubCategory>();
            ShopCart = new HashSet<ShopCart>();
        }

        public int Id { get; set; }
        public string Description { get; set; }
        public decimal UnitPrice { get; set; }
        public int Stock { get; set; }
        public byte[] Image { get; set; }

        public virtual ICollection<ProductSubCategory> ProductSubCategory { get; set; }
        public virtual ICollection<ShopCart> ShopCart { get; set; }
    }
}