// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data
{
    public partial class ProductSubCategory
    {
        public int Id { get; set; }
        public int IdProduct { get; set; }
        public int IdSubcategory { get; set; }

        public virtual Product IdProductNavigation { get; set; }
        public virtual SubCategory IdSubcategoryNavigation { get; set; }
    }
}