// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data
{
    public partial class ShopCart
    {
        public int Id { get; set; }
        public int IdClient { get; set; }
        public int IdProduct { get; set; }
        public int Stock { get; set; }
        public decimal ProductSubtotal { get; set; }
        public decimal CartSubtotal { get; set; }

        public virtual Users IdClientNavigation { get; set; }
        public virtual Product IdProductNavigation { get; set; }
    }
}