// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data
{
    public partial class SubCategory
    {
        public SubCategory()
        {
            CategorySubCategory = new HashSet<CategorySubCategory>();
            ProductSubCategory = new HashSet<ProductSubCategory>();
        }

        public int Id { get; set; }
        public string Description { get; set; }
        public bool Show { get; set; }

        public virtual ICollection<CategorySubCategory> CategorySubCategory { get; set; }
        public virtual ICollection<ProductSubCategory> ProductSubCategory { get; set; }
    }
}