// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data
{
    public partial class Users
    {
        public Users()
        {
            IssueIdAdminNavigation = new HashSet<Issue>();
            IssueIdClientNavigation = new HashSet<Issue>();
            ShopCart = new HashSet<ShopCart>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public DateTime DateBirth { get; set; }
        public long Dni { get; set; }
        public long Phone { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public int IdHome { get; set; }
        public int IdRol { get; set; }

        public virtual Home IdHomeNavigation { get; set; }
        public virtual Rol IdRolNavigation { get; set; }
        public virtual ICollection<Issue> IssueIdAdminNavigation { get; set; }
        public virtual ICollection<Issue> IssueIdClientNavigation { get; set; }
        public virtual ICollection<ShopCart> ShopCart { get; set; }
    }
}